export type RiskLevel =
    | "LOW"
    | "MEDIUM"
    | "HIGH";

export type RiskSeverity =
    | "LOW"
    | "MEDIUM"
    | "HIGH";

export type RecommendationPriority =
    | "LOW"
    | "MEDIUM"
    | "HIGH";

export interface RiskFeatures {
    project_progress: number;
    task_completion_rate: number;
    blocked_task_ratio: number;
    overdue_task_ratio: number;
    requirement_completion_rate: number;
    milestone_completion_rate: number;
    open_issue_count: number;
    critical_issue_count: number;
    api_test_failure_rate: number;
    avg_api_response_time_ms: number;
    technical_review_score: number;
    days_remaining: number;
    development_velocity: number;
}

export interface RiskProbabilities {
    LOW: number;
    MEDIUM: number;
    HIGH: number;
}

// Raw factor returned by Python ML service
export interface MLRiskFactor {
    feature: string;
    value: number;
    impact: number;
}

export interface RiskPrediction {
    risk_level: RiskLevel;

    probabilities: RiskProbabilities;

    // Raw SHAP factors returned by Python.
    risk_factors: MLRiskFactor[];
}

// Human-readable factor generated by Node.js
export interface RiskFactor {
    factor: string;
    value: number;

    // Presentation priority based on SHAP contribution ranking.
    // This is not an objective real-world severity measurement.
    severity: RiskSeverity;

    explanation: string;
}

export interface RecommendedAction {
    priority: RecommendationPriority;
    action: string;
    reason: string;
}

export interface RiskExplanation {
    riskLevel: RiskLevel;
    summary: string;
    riskFactors: RiskFactor[];
    recommendedActions: RecommendedAction[];
}

export interface RiskData {
    projectId: number;

    features: RiskFeatures;

    prediction: RiskPrediction;

    explanation: RiskExplanation;
}